Video Call V1
wxsd-sales/video-queue pull request #1
Opened 2023-01-18 03:43 UTC by akoushke

WIP

2023-01-18 03:44 UTC, akoushke commented on package.json
> +    "moment": "^2.29.4",
remove momenet and use local Date

2023-01-18 17:36 UTC, akoushke commented on src/routes/auth/device.svelte
> +<script lang="ts">
remove this file.

2023-01-18 17:37 UTC, akoushke commented on src/routes/auth/index.svelte
> +        src="https://app.vidcast.io/share/embed/013bee2d-4aff-4921-b760-599ad96dff43"
make this a constant

2023-01-18 17:40 UTC, akoushke commented on src/routes/demos/save/.Part0DemoFields.svelte
> +      A "Demo" is a collection of sessions along with brand logo, background, sensors etc. that creates a customizable
reword this.

2023-01-18 17:40 UTC, akoushke commented on src/routes/demos/save/.Part0DemoFields.svelte
> +        placeholder="WXSD Support Demo"
Video Calling Queue Demo

2023-01-18 17:41 UTC, akoushke commented on src/routes/demos/save/.Part3MeetingTypesOptionsFields.svelte
> +  <!-- <div class="column is-one-third">
WIP V2

2023-01-18 17:43 UTC, akoushke commented on src/routes/demos/save/index.ts
> +  console.log(formData);
remove this

2023-01-18 17:46 UTC, akoushke commented on src/routes/index.ts
>  export const GET = async (requestEvent: RequestEvent) => {
remove requestEvent

2023-01-20 20:50 UTC, askmrsinh requested changes
Please see comments.

2023-01-20 20:50 UTC, askmrsinh commented on src/routes/sessions/[uuid]/requester/index.svelte
> +        </div>
Maybe vertical layout for the radio buttons will look better?

2023-01-20 20:50 UTC, askmrsinh commented on src/routes/sessions/[uuid]/requester/index.svelte
> +    <h1 class="is-size-3 has-text-white">Submit Request</h1>
Add the `.title` class for constancy.

2023-01-20 20:50 UTC, askmrsinh commented on src/routes/sessions/[uuid]/responder/index.svelte
> +    <h1 class="is-size-3 has-text-white">Request Queue</h1>
Add the `.title` class for consistency.

2023-01-20 20:50 UTC, askmrsinh commented on src/routes/sessions/[uuid]/responder/index.svelte
> +<hr />
Removing this gives vertical space to the video.

2023-01-20 20:50 UTC, askmrsinh commented on src/routes/sessions/[uuid]/requester/index.svelte
> +<hr />
Removing this gives vertical space to the video.

2023-01-20 20:50 UTC, askmrsinh commented on src/routes/sessions/[uuid]/responder/index.svelte
> +  // };
Remove or move to different branch.

2023-01-20 20:50 UTC, askmrsinh commented on src/hooks.ts
> +      ...{ entities: [entity.Session, entity.User, entity.Data, entity.Demo] }
I understand that same activation flow won't apply hence this has been removed. But consider adding some instructions on:
- How to enable kiosk mode.
- How to set the two URLs.
- What settings should be enabled on the devices for things to work.

2023-01-20 20:50 UTC, askmrsinh commented on src/lib/constants.ts
> +export const INSTANT_CONNECT_GETTING_STARTED_URL = 'https://instant.webex.com';
Most of these should go in `env.example` file. Also remove any other env variables there that you do not plan to use.

2023-01-20 22:23 UTC, akoushke commented on src/routes/demos/save/index.ts
> +    public readonly meetingTypes!: Array<MEETING_TYPE_OPTIONS>;
IMO its easier to have an array in case of adding or removing an option without updating the database structure.

2023-01-21 01:07 UTC, akoushke commented on src/hooks.ts
> +      ...{ entities: [entity.Session, entity.User, entity.Data, entity.Demo] }
I will work on on this page after first deployement

2023-01-23 16:17 UTC, askmrsinh commented on src/routes/sessions/[uuid]/.Requester.svelte
> +  let isOnMobile: boolean = browser && window.screen.availWidth < 480;
Specifying types here is redundant. I feel linter/prettier settings should be updated to automatically handle this.

2023-01-23 16:20 UTC, askmrsinh commented on src/lib/environment.ts
> -
In next PR, corresponding entries in `.env.example` should also be removed.

2023-01-23 16:24 UTC, askmrsinh commented on src/components/RequestDetails/RequestDetails.svelte
> +  export const FORCE_CLOSE_REQUEST = 'force-close-request';
Seems redundant (already imported via `import { CLOSE_REQUEST, FORCE_CLOSE_REQUEST } from '$lib/constants'`).

2023-01-23 16:27 UTC, askmrsinh approved these changes
Some comments need to be addressed in a future PR.

2023-01-23 16:30 UTC, merged